server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  banner:
    location: static/banner.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.18.26.201:1521:TF
      username: TF
      password: TF
      initialSize: 5
      maxActive: 20
      ## 配置获取连接等待超时的时间
      maxWait: 60000
      ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      ## 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
    cluster:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.18.26.36:3306/tx?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Asia/Shanghai&autoReconnect=true
      password: root
      username: root
      initialSize: 5
      maxActive: 30
      ## 配置获取连接等待超时的时间
      maxWait: 60000
      ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      ## 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
    druid:
      aop-patterns: com.tangl.demo.controller.*,com.tangl.demo.service.*
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow:
        login-username:
        login-password:
        #禁止那些ip
        deny:
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    password:
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
logging:
  file:
    path: G:/javaWorkSpace/springBootDemo/
    name: springbootdemo.log
# actuator监控
management:
  server:
    # 设置监控服务端口
    port: 8080
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
info: #下面的值全部自定义即可
  app:
    name: springBootDemo
    version: v1.0.0
    encoding: @project.build.sourceEncoding@  #应用编码
    java:
      source: @java.version@  #jdk 版本
      target: @java.version@  #jdk 版本
  author:
    name: tangliang  #作者姓名
    phone: 15566418409  #作者联系方式
http:
  maxTotal: 500 #设置连接总数
  defaultMaxPerRoute: 100 #设置每个主机最大的并发数
  connectTimeout: 2000 #设置创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 6000 #数据传输的最长时间
  maxIdleTime: 1 #空闲时间(用于定期清理空闲连接)
  waitTime: 30000
  idleConTime: 3
  retryCount: 3
  validateAfterInactivity: 1000
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /



