server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  banner:
    location: static/banner.txt
  profiles:
    active: druid
    #切换配置文件
  #    spring.profiles.include: druid,ddd
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    password:
    database: 1
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  security:
    user:
      name: tang
      password: tang
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: tl # mongodb的连接的数据库
logging:
  file:
    path: G:/javaWorkSpace/springBootDemo/
    name: springbootdemo.log
# actuator监控
management:
  security:
    enabled: true
  server:
    # 设置监控服务端口
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      base-path: /actuator #基本路径
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
        # 跨域处理
      cors:
        allowed-origins: http://localhost:8080/   #允许跨域的ip地址
        allowed-methods: post,delete,get,put #允许通过的请求，还有支持时间
info: #下面的值全部自定义即可
  app:
    name: springBootDemo
    version: v1.0.0
    encoding: @project.build.sourceEncoding@  #应用编码
    java:
      source: @java.version@  #jdk 版本
      target: @java.version@  #jdk 版本
  author:
    name: tangliang  #作者姓名
    phone: 15566418409  #作者联系方式
http:
  maxTotal: 500 #设置连接总数
  defaultMaxPerRoute: 100 #设置每个主机最大的并发数
  connectTimeout: 2000 #设置创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 6000 #数据传输的最长时间
  maxIdleTime: 1 #空闲时间(用于定期清理空闲连接)
  waitTime: 30000
  idleConTime: 3
  retryCount: 3
  validateAfterInactivity: 1000
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /
# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间



